# Generated by Django 5.0.6 on 2024-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unit',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
