# Generated by Django 5.0.6 on 2024-07-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_room_unit'),
        ('reservations', '0003_auto_20240715_1657'),
    ]

    operations = [
    ]
