# Generated by Django 5.0.7 on 2024-07-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_alter_room_unit_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="proof_of_payment",
            field=models.FileField(
                blank=True, null=True, upload_to="proofs_of_payment/"
            ),
        ),
        migrations.CreateModel(
            name="ProofOfPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="proofs_of_payment/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.booking",
                    ),
                ),
            ],
        ),
    ]
