# Generated by Django 5.0.6 on 2024-07-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_booking_proof_of_payment_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
